In [1]:
import pandas as pd
import os

In [2]:
names = ['user_id', 'movie_id', 'rating', 'timestamp']
train1 = pd.read_csv(os.path.join('ml-100k', 'u2.base'), '\t', names=names,engine='python')
train1.drop(['timestamp'], axis = 1)

user_id  movie_id  rating
0            1         3       4
1            1         4       3
2            1         5       3
3            1         6       5
4            1         7       4
...        ...       ...     ...
79995      943      1067       2
79996      943      1074       4
79997      943      1188       3
79998      943      1228       3
79999      943      1330       3

[80000 rows x 3 columns]

In [3]:
test1 = pd.read_csv(os.path.join('ml-100k', 'u2.test'), '\t', names=names,engine='python')
test1.drop(['timestamp'], axis = 1)

user_id  movie_id  rating
0            1         1       5
1            1         2       3
2            1         8       1
3            1         9       5
4            1        21       1
...        ...       ...     ...
19995      655       693       3
19996      655       736       3
19997      655       918       2
19998      655      1403       3
19999      658       276       4

[20000 rows x 3 columns]

In [4]:
comp_data = pd.read_csv(os.path.join('ml-100k', 'u2.base'), '\t', names=names,engine='python')
user_data = comp_data.pivot(index = 'user_id', columns = 'movie_id', values = 'rating').fillna(0)
user_data.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          0.0   0.0   4.0   3.0   3.0   5.0   4.0   0.0   0.0   3.0  ...   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1648 columns]

In [5]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_data)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)
print(user_similarity.shape)

[[1.         0.10701614 0.01177757 ... 0.09433333 0.16143831 0.36340433]
 [0.10701614 1.         0.08631615 ... 0.09613523 0.15778882 0.09695597]
 [0.01177757 0.08631615 1.         ... 0.04592206 0.12445144 0.01419628]
 ...
 [0.09433333 0.09613523 0.04592206 ... 1.         0.1016418  0.09511958]
 [0.16143831 0.15778882 0.12445144 ... 0.1016418  1.         0.18246466]
 [0.36340433 0.09695597 0.01419628 ... 0.09511958 0.18246466 1.        ]]
(943, 943)


In [6]:
neighbours = user_similarity[user_similarity[:,1] > 0.5]

In [7]:
user_similarity[user_similarity< 0.5] = 0.0
#ini_array1[ini_array1<0] = 0

In [8]:
print(user_similarity)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [9]:
print(user_similarity.shape)


(943, 943)


In [10]:
train1_piv = train1.pivot(index = 'user_id', columns = 'movie_id', values = 'rating').fillna(0)
test1_piv = test1.pivot(index = 'user_id', columns = 'movie_id', values = 'rating').fillna(0)

In [11]:
user_predicted_ratings = np.dot(user_similarity, user_data)
user_predicted_ratings

array([[4.68856333, 3.6459619 , 5.57333152, ..., 0.        , 0.        ,
        1.57333152],
       [2.69122518, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [6.50507087, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [3.71859175, 6.64282464, 1.64282464, ..., 0.        , 0.        ,
        0.        ]])

In [12]:
user_predicted_ratings.shape

(943, 1648)

In [13]:
dummy_train = train1.copy()
dummy_test = test1.copy()

dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x > 0 else 1)
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x > 0 else 0)

In [14]:
user_predicted_ratings.shape

(943, 1648)

In [15]:
# The movies not rated by user is marked as 1 for prediction 
dummy_train = dummy_train.pivot(index = 'user_id', columns = 'movie_id', values = 'rating').fillna(1)

# The movies not rated by user is marked as 0 for evaluation 
dummy_test = dummy_test.pivot(index ='user_id', columns = 'movie_id', values = 'rating').fillna(0)

In [16]:
user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)
user_final_ratings.head()

movie_id      1         2     3     4     5     6     7         8     \
user_id                                                                
1         4.688563  3.645962   0.0   0.0   0.0   0.0   0.0  2.590788   
2         2.691225  0.000000   0.0   0.0   0.0   0.0   0.0  0.000000   
3         0.000000  0.000000   0.0   0.0   0.0   0.0   0.0  0.000000   
4         0.000000  0.000000   0.0   0.0   0.0   0.0   0.0  0.000000   
5         0.000000  0.000000   0.0   0.0   0.0   0.0   0.0  0.000000   

movie_id      9     10    ...  1673  1674  1675  1676  1677  1678  1679  1680  \
user_id                   ...                                                   
1         5.213007   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2         0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3         0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4         0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5         0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

movie_id  1681      1682  
user_id                   
1          0.0  1.573332  
2          0.0  0.000000  
3          0.0  0.000000  
4          0.0  0.000000  
5          0.0  0.000000  

[5 rows x 1648 columns]

In [17]:
test_user_features = test1.pivot(index = 'user_id', columns = 'movie_id', values = 'rating').fillna(0)
test_user_similarity = cosine_similarity(test_user_features)
test_user_similarity[np.isnan(test_user_similarity)] = 0

print(test_user_similarity)
print("- "*10)
print(test_user_similarity.shape)

[[1.         0.04322004 0.09526993 ... 0.         0.         0.        ]
 [0.04322004 1.         0.02661127 ... 0.07815973 0.06174421 0.23735633]
 [0.09526993 0.02661127 1.         ... 0.06563333 0.         0.        ]
 ...
 [0.         0.07815973 0.06563333 ... 1.         0.         0.        ]
 [0.         0.06174421 0.         ... 0.         1.         0.        ]
 [0.         0.23735633 0.         ... 0.         0.         1.        ]]
- - - - - - - - - - 
(653, 653)


In [18]:
test_user_similarity[test_user_similarity< 0.5] = 0.0

In [19]:
user_predicted_ratings_test = np.dot(test_user_similarity, test_user_features)
user_predicted_ratings_test

array([[5., 3., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
test_user_final_rating = np.multiply(user_predicted_ratings_test, dummy_test)
test_user_final_rating.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   0.0   0.0   0.0   0.0   0.0   1.0   5.0   0.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

movie_id  1603  1605  1608  1615  1616  1617  1619  1620  1623  1624  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1420 columns]

In [21]:
train1['rating'].describe()

count    80000.000000
mean         3.526463
std          1.124429
min          1.000000
25%          3.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: rating, dtype: float64

In [22]:
from sklearn.preprocessing import MinMaxScaler

X = test_user_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[2.22576527 2.75              nan ...        nan        nan        nan]
 [1.79432396        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [23]:
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

20000

In [24]:
test = test1.pivot(index = 'user_id', columns = 'movie_id', values = 'rating')
test.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   NaN   NaN   NaN   NaN   NaN   1.0   5.0   NaN  ...   
2          4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

movie_id  1603  1605  1608  1615  1616  1617  1619  1620  1623  1624  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 1420 columns]

In [25]:
# Mean abslute error

mae = np.abs(pred - test).sum().sum()/total_non_nan
print(mae)

0.5583905153220869
